### PR TITLE
Create Blockchain useful links

### PR DESCRIPTION
**Pull request by abhaysap**

### CODE REVIEW

**Comment by abhaysap** [comment]
blockchain links

**Comment by anistark** [comment]
This has to be written in the `README.md` file in the format written there under specific sections.

**Comment by abhaysap** [comment]
uplods were disabled for me so added resources in noted pad and uploaded ot...
RegardsAbhay Sapru+919930653403 

    On Wednesday, 13 February, 2019, 12:25:54 am IST, Kumar Anirudha <notifications@github.com> wrote:  
 
 
This has to be written in the README.md file in the format written there under specific sections.

**Comment by anistark** [comment]
It's not supposed to be uploaded anyway. Since you opened another PR.

Closing this.

**Pull request closed without merging**
